"""photos and voice notes

Revision ID: 29049a736ba6
Revises: 36bebe426b81
Create Date: 2026-05-15 20:30:15.714571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29049a736ba6'
down_revision: Union[str, None] = '36bebe426b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('audio_path', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_provider', sa.String(length=64), nullable=True),
    sa.Column('transcript_language', sa.String(length=16), nullable=True),
    sa.Column('transcription_status', sa.String(length=32), nullable=False),
    sa.Column('transcription_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('transcribed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_notes_project_id'), 'voice_notes', ['project_id'], unique=False)
    op.create_table('project_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.Integer(), nullable=True),
    sa.Column('daily_report_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('annotated_path', sa.String(length=1024), nullable=True),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geo_lat', sa.Float(), nullable=True),
    sa.Column('geo_lng', sa.Float(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['daily_report_id'], ['daily_reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_photos_project_id'), 'project_photos', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_photos_sha256'), 'project_photos', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_photos_sha256'), table_name='project_photos')
    op.drop_index(op.f('ix_project_photos_project_id'), table_name='project_photos')
    op.drop_table('project_photos')
    op.drop_index(op.f('ix_voice_notes_project_id'), table_name='voice_notes')
    op.drop_table('voice_notes')
    # ### end Alembic commands ###
