"""heating design schema

Revision ID: f5dc4ba4bc32
Revises: 26d032f184e6
Create Date: 2026-05-15 19:56:59.875324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5dc4ba4bc32'
down_revision: Union[str, None] = '26d032f184e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heating_designs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('system_type', sa.String(length=64), nullable=True),
    sa.Column('supply_temp_c', sa.Float(), nullable=True),
    sa.Column('return_temp_c', sa.Float(), nullable=True),
    sa.Column('delta_t_k', sa.Float(), nullable=True),
    sa.Column('pump_head_pa', sa.Float(), nullable=True),
    sa.Column('total_volume_flow_lph', sa.Float(), nullable=True),
    sa.Column('pump_model', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_file', sa.String(length=512), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('imported_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['imported_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('heating_circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('design_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('strand', sa.String(length=128), nullable=True),
    sa.Column('room', sa.String(length=255), nullable=True),
    sa.Column('floor', sa.String(length=64), nullable=True),
    sa.Column('radiator_type', sa.String(length=255), nullable=True),
    sa.Column('heat_load_w', sa.Float(), nullable=True),
    sa.Column('volume_flow_lph', sa.Float(), nullable=True),
    sa.Column('pressure_drop_pa', sa.Float(), nullable=True),
    sa.Column('pipe_length_m', sa.Float(), nullable=True),
    sa.Column('valve_type', sa.String(length=255), nullable=True),
    sa.Column('valve_preset', sa.String(length=64), nullable=True),
    sa.Column('kv_value', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['design_id'], ['heating_designs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('heating_circuits')
    op.drop_table('heating_designs')
    # ### end Alembic commands ###
